stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./images/app/Dockerfile
      buildContext: .
      tag: practical
      registry: 127.0.0.1:34207
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./manifests/app-deployment.yaml
timeout: 60
notification: {}
